export const ADMIN_ADD_SUCESS = 'ADMIN_ADD_SUCESS'
export const ADMIN_ADD_FAIL = 'ADMIN_ADD_FAIL'

export const ADMIN_GET_SUCESS = 'ADMIN_GET_SUCESS'
export const ADMIN_GET_FAIL = 'ADMIN_GET_FAIL'

export const ADMIN_UPDATE_SUCESS = 'ADMIN_UPDATE_SUCESS'
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL'

export const ADMIN_DELETE_SUCESS = 'ADMIN_DELETE_SUCESS'
export const ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL'