export const CATEGORY_ADD_SUCESS = 'CATEGORY_ADD_SUCESS'
export const CATEGORY_ADD_FAIL = 'CATEGORY_ADD_FAIL'

export const CATEGORY_GET_SUCESS = 'CATEGORY_GET_SUCESS'
export const CATEGORY_GET_FAIL = 'CATEGORY_GET_FAIL'

export const CATEGORY_DELETE_SUCESS = 'CATEGORY_DELETE_SUCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'

export const CATEGORY_UPDATE_SUCESS = 'CATEGORY_UPDATE_SUCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
