export const MATCH_ADD_SUCESS = 'MATCH_ADD_SUCESS'
export const MATCH_ADD_FAIL = 'MATCH_ADD_FAIL'

export const MATCH_GET_SUCESS = 'MATCH_GET_SUCESS'
export const MATCH_GET_FAIL = 'MATCH_GET_FAIL'

export const MATCH_UPDATE_SUCESS = 'MATCH_UPDATE_SUCESS'
export const MATCH_UPDATE_FAIL = 'MATCH_UPDATE_FAIL'

export const MATCH_DELETE_SUCESS = 'MATCH_DELETE_SUCESS'
export const MATCH_DELETE_FAIL = 'MATCH_DELETE_FAIL'