export const PARAMETER_ADD_SUCESS = 'PARAMETER_ADD_SUCESS'
export const PARAMETER_ADD_FAIL = 'PARAMETER_ADD_FAIL'

export const PARAMETER_GET_SUCESS = 'PARAMETER_GET_SUCESS'
export const PARAMETER_GET_FAIL = 'PARAMETER_GET_FAIL'

export const PARAMETER_DELETE_SUCESS = 'PARAMETER_DELETE_SUCESS'
export const PARAMETER_DELETE_FAIL = 'PARAMETER_DELETE_FAIL'

export const PARAMETER_UPDATE_SUCESS = 'PARAMETER_UPDATE_SUCESS'
export const PARAMETER_UPDATE_FAIL = 'PARAMETER_UPDATE_FAIL'