export const PLAYER_ADD_SUCESS = 'PLAYER_ADD_SUCESS'
export const PLAYER_ADD_FAIL = 'PLAYER_ADD_FAIL'

export const PLAYER_GET_SUCESS = 'PLAYER_GET_SUCESS'
export const PLAYER_GET_FAIL = 'PLAYER_GET_FAIL'

export const PLAYER_DELETE_SUCESS = 'PLAYER_DELETE_SUCESS'
export const PLAYER_DELETE_FAIL = 'PLAYER_DELETE_FAIL'

export const PLAYER_UPDATE_SUCESS = 'PLAYER_UPDATE_SUCESS'
export const PLAYER_UPDATE_FAIL = 'PLAYER_UPDATE_FAIL'





