export const POSITION_ADD_SUCESS = 'POSITION_ADD_SUCESS'
export const POSITION_ADD_FAIL = 'POSITION_ADD_FAIL'

export const POSITION_GET_SUCESS = 'POSITION_GET_SUCESS'
export const POSITION_GET_FAIL = 'POSITION_GET_FAIL'
export const POSITION_SUCESS_MSG_CLEAR = 'POSITION_SUCESS_MSG_CLEAR'


export const POSITION_DELETE_SUCESS = 'POSITION_DELETE_SUCESS'
export const POSITION_DELETE_FAIL = 'POSITION_DELETE_FAIL'

export const POSITION_UPDATE_SUCESS = 'POSITION_UPDATE_SUCESS'
export const POSITION_UPDATE_FAIL = 'POSITION_UPDATE_FAIL'
