export const TEAM_ADD_SUCESS = 'TEAM_ADD_SUCESS'
export const TEAM_ADD_FAIL = 'TEAM_ADD_FAIL'

export const TEAM_GET_SUCESS = 'TEAM_GET_SUCESS'
export const TEAM_GET_FAIL = 'TEAM_GET_FAIL'

export const TEAM_UPDATE_SUCESS = 'TEAM_UPDATE_SUCESS'
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL'

export const TEAM_DELETE_SUCESS = 'TEAM_DELETE_SUCESS'
export const TEAM_DELETE_FAIL = 'TEAM_DELETE_FAIL'