export const VIDEO_ADD_SUCESS = 'VIDEO_ADD_SUCESS'
export const VIDEO_ADD_FAIL = 'VIDEO_ADD_FAIL'

export const VIDEO_GET_SUCESS = 'VIDEO_GET_SUCESS'
export const VIDEO_GET_FAIL = 'VIDEO_GET_FAIL'

export const VIDEO_UPDATE_SUCESS = 'VIDEO_UPDATE_SUCESS'
export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL'

export const VIDEO_DELETE_SUCESS = 'VIDEO_DELETE_SUCESS'
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL'